#
# Global StyLua configuration used by Neovim <Leader>cf key mapping
#
indent_type = "Spaces"
indent_width = 2
column_width = 140
quote_style = "AutoPreferDouble"
call_parentheses = "None"
block_newline_gaps = "Preserve"
collapse_simple_statement = "Never"
