os:
  editPreset: "nvim"

gui:
  skipDiscardChangeWarning: true
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - "#404040"

git:
  paging:
    pager: delta --dark --paging=never --24-bit-color=never
